import { nanoid } from 'nanoid';

import clockwise from '@/assets/clockwise.jpeg';
import cleveroad from '@/assets/cleveroad.jpeg';
import civenty from '@/assets/civenty.jpeg';
import { IEmploymentHistory } from '@/types/IEmploymentHistory';

export const employmentHistory: ReadonlyArray<IEmploymentHistory> = [
  {
    id: '1',
    company: {
      image: clockwise,
      title: 'Clockwise Software',
    },
    position: 'Frontend Developer',
    period: {
      start: '2021-10-25T09',
      end: '2023-02-25T09',
    },
    responsibilities: [
      { id: nanoid(), responsibility: 'cross-browser markup' },
      { id: nanoid(), responsibility: 'teamwork with an international team' },
      { id: nanoid(), responsibility: 'adaptive markup according to grid system' },
      { id: nanoid(), responsibility: 'features, bugs fixes' },
      {
        id: nanoid(),
        responsibility:
          'implement widgets with different comlexity according to clear logic, clean code, and best practices',
      },
      { id: nanoid(), responsibility: 'work with ui/ux and ba team for the most effective solution' },
      { id: nanoid(), responsibility: 'code review' },
    ],
    technologyStack: [
      { id: nanoid(), tag: 'javascript' },
      { id: nanoid(), tag: 'typescript' },
      { id: nanoid(), tag: 'react' },
      { id: nanoid(), tag: 'redux(redux-thunk, redux-toolkit, rtk-query)' },
      { id: nanoid(), tag: 'CRUD' },
      { id: nanoid(), tag: 'jest' },
      { id: nanoid(), tag: 'react-testing-library' },
      { id: nanoid(), tag: 'html' },
      { id: nanoid(), tag: 'css' },
      { id: nanoid(), tag: 'scss' },
      { id: nanoid(), tag: 'sass' },
      { id: nanoid(), tag: 'bem' },
      { id: nanoid(), tag: 'material-ui' },
      { id: nanoid(), tag: 'styled-components (css-in-js)' },
      { id: nanoid(), tag: 'webpack' },
      { id: nanoid(), tag: 'bootstrap' },
      { id: nanoid(), tag: 'formik' },
      { id: nanoid(), tag: 'react-hook-forms' },
      { id: nanoid(), tag: 'storybook' },
      { id: nanoid(), tag: 'git' },
      { id: nanoid(), tag: 'npm' },
      { id: nanoid(), tag: 'yarn' },
      { id: nanoid(), tag: 'eslint' },
      { id: nanoid(), tag: 'prettier' },
      { id: nanoid(), tag: 'jira' },
      { id: nanoid(), tag: 'trello' },
      { id: nanoid(), tag: 'photoshop' },
      { id: nanoid(), tag: 'figma' },
    ],
  },
  {
    id: '2',
    company: {
      image: cleveroad,
      title: 'Cleveroad',
    },
    position: 'Frontend Developer',
    period: {
      start: '2021-02-25T09',
      end: '2021-10-25T09',
    },
    responsibilities: [
      { id: nanoid(), responsibility: 'cross-browser markup' },
      { id: nanoid(), responsibility: 'adaptive markup for different gadgets' },
      { id: nanoid(), responsibility: 'performance optimization' },
      { id: nanoid(), responsibility: 'work with ui/ux and ba team for the most effective solution' },
      { id: nanoid(), responsibility: 'code review' },
    ],
    technologyStack: [
      { id: nanoid(), tag: 'javascript' },
      { id: nanoid(), tag: 'typescript' },
      { id: nanoid(), tag: 'react' },
      { id: nanoid(), tag: 'gatsby' },
      { id: nanoid(), tag: 'redux(redux-saga, redux-thunk)' },
      { id: nanoid(), tag: 'CRUD' },
      { id: nanoid(), tag: 'html' },
      { id: nanoid(), tag: 'css' },
      { id: nanoid(), tag: 'scss' },
      { id: nanoid(), tag: 'sass' },
      { id: nanoid(), tag: 'bem' },
      { id: nanoid(), tag: 'webpack' },
      { id: nanoid(), tag: 'bootstrap' },
      { id: nanoid(), tag: 'formik' },
      { id: nanoid(), tag: 'react-hook-forms' },
      { id: nanoid(), tag: 'git' },
      { id: nanoid(), tag: 'npm' },
      { id: nanoid(), tag: 'yarn' },
      { id: nanoid(), tag: 'eslint' },
      { id: nanoid(), tag: 'prettier' },
      { id: nanoid(), tag: 'jira' },
      { id: nanoid(), tag: 'photoshop' },
      { id: nanoid(), tag: 'figma' },
    ],
  },
  {
    id: '3',
    company: {
      image: civenty,
      title: 'Civenty',
    },
    position: 'Frontend Developer',
    period: {
      start: '2019-06-25T09',
      end: '2020-01-25T09',
    },
    responsibilities: [
      { id: nanoid(), responsibility: 'cross-browser markup' },
      { id: nanoid(), responsibility: 'adaptive markup for different gadgets' },
      { id: nanoid(), responsibility: 'work with animation' },
      { id: nanoid(), responsibility: 'setup project builders' },
      { id: nanoid(), responsibility: 'work with design' },
      { id: nanoid(), responsibility: 'work with two projects at one time' },
    ],
    technologyStack: [
      { id: nanoid(), tag: 'javascript' },
      { id: nanoid(), tag: 'jquery' },
      { id: nanoid(), tag: 'react' },
      { id: nanoid(), tag: 'html' },
      { id: nanoid(), tag: 'css' },
      { id: nanoid(), tag: 'scss' },
      { id: nanoid(), tag: 'sass' },
      { id: nanoid(), tag: 'less' },
      { id: nanoid(), tag: 'bem' },
      { id: nanoid(), tag: 'webpack' },
      { id: nanoid(), tag: 'gulp' },
      { id: nanoid(), tag: 'twig' },
      { id: nanoid(), tag: 'bootstrap' },
      { id: nanoid(), tag: 'git' },
      { id: nanoid(), tag: 'jira' },
      { id: nanoid(), tag: 'photoshop' },
      { id: nanoid(), tag: 'figma' },
    ],
  },
] as const;
